Remove asm label from ec_verify.C
It does not seem to be needed but it causes trouble
when this code is built as a library and it is linked against:

  undefined reference to `.L.ec_verify'

Change-Id: If1daae54946e879caf5494e5205bea09088d87fe
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/c/hw/ekb-src/+/177399
Reviewed-by: Daniel Kiss <kiss@de.ibm.com>
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Tested-by: PPE CI <ppe-ci+hostboot@us.ibm.com>
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/c/hw/sbe/+/177400
Reviewed-by: Joseph J McGill <jmcgill@us.ibm.com>
Reviewed-by: Team <hostboot@us.ibm.com>