onetime: bldr: build: Fix, Race condition during pak generation
- Sometime we are hitting a race condition while building the
  bootloader pak file (vanilla image) that is, the actual bootloader
  binary size is varying in the pak file.

- The reason for the above issue is, we did not add the bootloader
  binary target as a dependency in the bootloader pak file generation
  target so fixed the same in this commit.

Tested:

- Without fix,

```
meson compile -C builddir/ -v obldr_package_img

...

[63/63] sbe/public/src/onetime/odyssey/bldr/build/utils/build.sh sbe/builddir/public/src/onetime/odyssey/bldr odyssey_bldr_DD1 sbe/public/src/import/public/common/utils/imageProcs/tools/paktool sbe/public/src/import/public/common/utils/imageProcs/tools/pakbuild sbe/public/src/build/utils/signHashList
FAILED: public/src/onetime/odyssey/bldr/odyssey_bldr_DD1.pak
sbe/public/src/onetime/odyssey/bldr/build/utils/build.sh sbe/builddir/public/src/onetime/odyssey/bldr odyssey_bldr_DD1 sbe/public/src/import/public/common/utils/imageProcs/tools/paktool sbe/public/src/import/public/common/utils/imageProcs/tools/pakbuild sbe/public/src/build/utils/signHashList
All output going to: sbe/builddir/public/src/onetime/odyssey/bldr/odyssey_bldr_DD1.*
Manifest file: sbe/public/src/onetime/odyssey/bldr/build/utils/manifest
  Validating manifest syntax
  Validating 'global' keyword values
  Validating 'layout' keyword values
  Building manifest paths
  ERROR: For layout entry 'boot/bldr.bin', the file is not found 'public/src/onetime/odyssey/bldr/odyssey_bldr_DD1.bin'
  CRITICAL: 1 error(s) found building the manifest!
  CRITICAL: Please correct the above errors and run again!
```

- With fix,

```
meson compile -C builddir/ -v obldr_package_img

...

[64/64] sbe/public/src/onetime/odyssey/bldr/build/utils/build.sh sbe/builddir/public/src/onetime/odyssey/bldr odyssey_bldr_DD1 sbe/public/src/import/public/common/utils/imageProcs/tools/paktool sbe/public/src/import/public/common/utils/imageProcs/tools/pakbuild sbe/public/src/build/utils/signHashList
All output going to: sbe/builddir/public/src/onetime/odyssey/bldr/odyssey_bldr_DD1.*
Manifest file: sbe/public/src/onetime/odyssey/bldr/build/utils/manifest
  Validating manifest syntax
  Validating 'global' keyword values
  Validating 'layout' keyword values
  Building manifest paths
Creating archive
Writing archive
All output in: sbe/builddir/public/src/onetime/odyssey/bldr
  Manifest: sbe/builddir/public/src/onetime/odyssey/bldr/odyssey_bldr_DD1.manifest
  Archive: sbe/builddir/public/src/onetime/odyssey/bldr/odyssey_bldr_DD1.pak

```

Change-Id: I3d223568c8434d286f7fd0de87da78c33c751718
Signed-off-by: Ramesh Iyyar <rameshi1@in.ibm.com>
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/147345
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Reviewed-by: Akhilesh S <akhis023@in.ibm.com>
Reviewed-by: Rajees P P <rajerpp1@in.ibm.com>
Reviewed-by: Sumit Kumar <sumit_kumar@in.ibm.com>
Reviewed-by: AMIT J TENDOLKAR <amit.tendolkar@in.ibm.com>